ALTER TABLE subnet_routes
  ADD COLUMN IF NOT EXISTS gateway_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS gateway_error TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gateway_checked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS gateway_out_interface TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gateway_route_interface TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gateway_lan_target TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS gateway_lan_reachable BOOLEAN NOT NULL DEFAULT false;
